Fix/apply info fix
Sungshin-PoHab/PoHab_Back pull request #13
Opened 2022-08-06 16:51 UTC by eunjungL

## 변경사항
1. startDate 추가에 따른 create/update logic 변경

## 중점적으로 볼 것
1. 오류 없이 잘 변경 됐는지 
2. 빠진 startDate 필요 부분은 없는지

2022-08-06 17:03 UTC, zinzo1019 approved these changes
넌 최고야 완벽해

2022-08-07 05:34 UTC, sunseo18 requested changes

2022-08-07 05:34 UTC, sunseo18 commented on src/main/java/com/example/pohab/Controller/StepController.java
>  @SpringBootApplication
혹쉬 이거 안 지우시나요???

2022-08-07 06:35 UTC, eunjungL commented on src/main/java/com/example/pohab/Controller/StepController.java
>  @SpringBootApplication
OH! 지워야지요 감사해용

2022-08-07 07:03 UTC, sunseo18 approved these changes
은정 최고

2022-08-07 13:20 UTC, merged